"""Tests for the textual DSL parser."""

import pytest

from packages.dsl_core.compiler import compile_textual_dsl
from packages.dsl_core.errors import ParseError
from packages.dsl_core.parser import parse

SIMPLE_SOURCE = """
app UserManagement {
  database: sqlite @path("./data/users.db")
  features: [cors, swagger]
}

entity User {
  email: string @required @email
  name: string @required
}

module Users for User
"""


def test_parser_parses_simple_program() -> None:
    """Parser builds a semantic AST for a simple DSL program."""
    program = parse(SIMPLE_SOURCE)

    assert program.app is not None
    assert program.app.name == "UserManagement"
    assert program.entities[0].name == "User"
    assert program.modules[0].name == "Users"
    assert program.modules[0].entity_name == "User"


def test_parser_rejects_entity_inside_module() -> None:
    """Top-level declarations are not valid inside module blocks."""
    source = """
module Users for User {
  entity User {
    email: string
  }
}
"""

    with pytest.raises(ParseError) as error:
        parse(source)

    assert "Routes are generated by convention" in str(error.value)


@pytest.mark.parametrize(
    "field_name",
    ["type", "enum", "module", "features", "database", "route", "dto", "app", "for"],
)
def test_parser_allows_keyword_field_names(field_name: str) -> None:
    """Reserved keywords are valid user-defined field names in field context."""
    blueprint = compile_textual_dsl(f"entity Product {{ {field_name}: string }}")

    fields = blueprint["modules"][0]["entity"]["fields"]
    assert fields[0]["name"] == field_name


def test_compiler_preserves_negative_annotation_values() -> None:
    """Signed numeric annotation values are emitted unchanged semantically."""
    blueprint = compile_textual_dsl(
        """
entity Reading {
  temperature: number @min(-20)
  score: number @default(-1)
  ratio: number @min(-0.5)
}
"""
    )

    fields = blueprint["modules"][0]["entity"]["fields"]
    assert fields[0]["validation"]["min"] == -20
    assert fields[1]["default"] == -1
    assert fields[2]["validation"]["min"] == -0.5
